# GAN Configuration File for Celebrity Faces

# Dataset settings
dataset:
  name: "celebrity"
  data_dir: "./data/celebrity"
  image_size: 64
  batch_size: 24  # Total batch size across all GPUs
  num_workers: 8
  max_images: 500  # Limit dataset size for faster training

# Model settings
model:
  latent_dim: 100
  generator:
    channels: [512, 256, 128, 64]
    kernel_size: 4
    stride: 2
    padding: 1
  discriminator:
    channels: [64, 128, 256, 512]
    kernel_size: 4
    stride: 2
    padding: 1

# Training settings
training:
  num_epochs: 1
  learning_rate:
    generator: 0.0002
    discriminator: 0.0002
  beta1: 0.5
  beta2: 0.999
  save_interval: 10
  log_interval: 50
  sample_interval: 200

# Output settings
output:
  checkpoint_dir: "./checkpoints_celebrity"
  sample_dir: "./samples_celebrity"
  log_dir: "./logs_celebrity"

# Hardware settings
device: "cuda"
seed: 42